# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r_github_packages:
  - phylotastic/rphylotastic
  - fmichonneau/phyloch
r_packages:
  - covr
  - data.table
  - ape
  - phytools
  - quadprog
  - igraph
after_success:
  - Rscript -e 'library(covr); codecov()'
