language: r
cache: packages
latex: false
r_github_packages:
  - phylotastic/rphylotastic
  - fmichonneau/phyloch
r_packages:
  - covr
  - data.table
after_success:
  - Rscript -e 'library(covr); codecov()'
fortran: false
env:
  - _R_CHECK_FORCE_SUGGESTS_=false
warnings_are_errors: false
os: osx

before_install:
- brew install git-lfs
- brew install imagemagick
